baseurl = "https://reynoldsbd.net/"
languageCode = "en-us"
title = "Bobby Reynolds"
theme = "HugoMDL"
MetaDataFormat = "yaml"
PygmentsCodeFences = true

[params]
  name = "Bobby Reynolds"
  description = "Thoughts on development, RE, and OS design and implementation"
  image = "/img/avatar.png"
  background = "/img/background.jpg"
  # mdlPrimary = "indigo"
  # mdlAccent = "pink"
  website = "reynoldsbd.net"
  email = "reynoldsbd3@hotmail.com"
  copyrightyear = "2016"
  frontpageposts = 6

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Articles"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "-140"
